### ISSUE TITLE
Can't add new actions

### ISSUE THREAD

**Issue by SDD701** [EnhancedJax/Combilaunch#3]
There is empty space when I press the plus
[https://imgur.com/a/CUk6nzO](url)

**Comment by EnhancedJax** [comment]
Hey, thanks for reporting the issue. Can I ask what version of windows are you on?

**Comment by SDD701** [comment]
> Hey, thanks for reporting the issue. Can I ask what version of windows are you on?

Windows 10 20H2, build 19042.985

**Comment by SDD701** [comment]
Yes, thank you. Closing the issue.
